export const GET_FILMS_REQUEST = 'GET_FILMS_REQUEST';
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS';
export const GET_FILMS_ERROR = 'GET_FILMS_ERROR';
export const GET_FILMS_FAIL = 'GET_FILMS_FAIL';

export const GET_FILM_REQUEST = 'GET_FILMS_REQUEST';
export const GET_FILM_SUCCESS = 'GET_FILM_SUCCESS';
export const GET_FILM_ERROR = 'GET_FILM_ERROR';
export const GET_FILM_FAIL = 'GET_FILM_FAIL';

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';

export const CHANGE_RATING = 'CHANGE_RATING';